### PR TITLE
New nouns glasses branch

### PR DESCRIPTION
**Pull request by fiveoceans-dev**
## Description

This traits where made for [www.nounsnation.com](http://www.nounsnation.com/). We want to submit these traits to the NounsDAO to continue CC0 movement.
Some of the traits are pretty good!

## Type of Change

- [x] Trait artwork submission
- [ ] Bug fix
- [ ] New feature
- [ ] Documentation update

## Trait Artwork Details

+square cross.png
+square peace.png
+square full purple.png
+square stereo.png
+square unicorn.png
+triple blue.png
+tripple teal.png
+square black dizzy.png
+square pink cyclope.png

### Trait Artwork Checklist:

- [x] Included traits are 32x32 pixel PNG images
- [x] Trait files are named appropriately
- [x] CC0 license agreement has been accepted

### CODE REVIEW

**Comment by fiveoceans-dev** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by fiveoceans-dev** [comment]
recheck

**Comment by fiveoceans-dev** [comment]
recheck

**Comment by fiveoceans-dev** [comment]
recheck

**Review by solimander — APPROVED** [review]
👏

**Pull request merged**
